// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_thank_you = "CgkIioLG8oQcEAIQEw"; // <GPGSID>
        public const string achievement_never_give_up = "CgkIioLG8oQcEAIQCA"; // <GPGSID>
        public const string achievement_should_not_be_happened = "CgkIioLG8oQcEAIQFA"; // <GPGSID>
        public const string achievement_marginal_utility = "CgkIioLG8oQcEAIQEA"; // <GPGSID>
        public const string achievement_pride_of_the_rich = "CgkIioLG8oQcEAIQCQ"; // <GPGSID>
        public const string achievement_voracity = "CgkIioLG8oQcEAIQEQ"; // <GPGSID>
        public const string achievement_perfect_itself = "CgkIioLG8oQcEAIQBQ"; // <GPGSID>
        public const string achievement_reading_the_field_manual = "CgkIioLG8oQcEAIQCg"; // <GPGSID>
        public const string achievement_sweety_fruition = "CgkIioLG8oQcEAIQBA"; // <GPGSID>
        public const string achievement_should_earn_a_nobel_prize = "CgkIioLG8oQcEAIQDg"; // <GPGSID>
        public const string achievement_science_theory = "CgkIioLG8oQcEAIQDQ"; // <GPGSID>
        public const string achievement_discovering_science = "CgkIioLG8oQcEAIQDA"; // <GPGSID>
        public const string achievement_seeing_the_starlight_at_the_stage = "CgkIioLG8oQcEAIQAg"; // <GPGSID>
        public const string achievement_admirable = "CgkIioLG8oQcEAIQEg"; // <GPGSID>
        public const string achievement_you_are_really_a_monster = "CgkIioLG8oQcEAIQBg"; // <GPGSID>
        public const string achievement_your_first_step = "CgkIioLG8oQcEAIQAQ"; // <GPGSID>
        public const string achievement_percentile_ignored = "CgkIioLG8oQcEAIQDw"; // <GPGSID>
        public const string achievement_starting_line_as_a_creator = "CgkIioLG8oQcEAIQBw"; // <GPGSID>
        public const string achievement_its_ok_dont_be_depressed = "CgkIioLG8oQcEAIQCw"; // <GPGSID>
        public const string achievement_platinum_on_stage = "CgkIioLG8oQcEAIQFg"; // <GPGSID>
        public const string achievement_nice_days_to_go_to_the_theater = "CgkIioLG8oQcEAIQAw"; // <GPGSID>

}

